### ISSUE TITLE
Bot uses only he/him pronounce

### ISSUE THREAD

**Issue by Roniakia** [TiraelSedai/RaterBot#27]
That's an issue. We can use AI to check avatars and nickname word gender for example.
But it will be better to have some options and a gender selector in it.

![image](https://user-images.githubusercontent.com/2908909/236578280-bc62dabf-7995-4fd6-b661-2ba5a0ba76aa.png)

UPD: I almost forgot, we also can check the profile description to see if they have pronounces in it.

**Comment by ilalex** [comment]
Fixed it.
