### ISSUE TITLE
[suggestion] Detect grouped images and re-upload them as a group

### ISSUE THREAD

**Issue by Brawlence** [TiraelSedai/RaterBot#6]
One can detect the media group the image belongs to by noting the **media_group_id** field of the message object: https://core.telegram.org/bots/api#message

And the method to send grouped media is described as follows: https://core.telegram.org/bots/api#sendmediagroup

**Comment by TiraelSedai** [comment]
It is probably the only sane solution, I'll do it shortly after new year
